function result = Hamil_10(kx,ky,a_moire)

%% Construct 10*10 ten band model Hamiltonian. unit (meV)
% input kx, ky, a_moire
t_ham=130; %
deltaV=1; % Add perturbation, [0,1]

%% Hopping parameters
t_eta=32.5; % meV
delta_pz=-0.1*t_eta;
delta_p_pm=0*t_eta;
delta_kappa=0.11*t_eta;
t_pz=0*t_eta;
t_p_pm=0.003*t_eta;
t_pp_pos=0*t_eta;
t_pp_neg=0.004*t_eta;
t_kappa=0*t_eta;
t_kappa_prime=0*t_eta;
t_ppz_pos=0.016*t_eta;
t_ppz_neg=0*t_eta;
t_kappap_pm_pos=0.016*t_eta;
t_kappap_pm_neg=-0.016*t_eta;
t_eta_psi=i*t_eta;

a=0.110;
b=0.033;
c=0.033;
d=0.573;

u_pz=-6*t_pz+delta_pz;
u_p_pm=3*t_p_pm+delta_p_pm;
u_kappa=-4*(t_kappa+t_kappa_prime)+delta_kappa;

omega=exp(i*2*pi/3);
Zeta=exp(i*2*pi/6);

p011110hc=(b6(kx,ky,0,1,a_moire)+b6(kx,ky,1,1,a_moire)+b6(kx,ky,1,0,a_moire)...
        +b6(kx,ky,0,1,a_moire)'+b6(kx,ky,1,1,a_moire)'+b6(kx,ky,1,0,a_moire)');
    
    H_pz=t_pz*p011110hc;


    C_pp=t_pp_pos*(b6(kx,ky,0,1,a_moire)+b6(kx,ky,-1,-1,a_moire)*omega+b6(kx,ky,1,0,a_moire)*omega')+...
        t_pp_neg*(b6(kx,ky,0,-1,a_moire)+b6(kx,ky,1,1,a_moire)*omega+b6(kx,ky,-1,0,a_moire)*omega');

    H_p_pm=t_p_pm*p011110hc*eye(2)+[0 C_pp';C_pp 0];

    C_ppz=i*t_ppz_pos*...
        [b6(kx,ky,0,1,a_moire)+b6(kx,ky,-1,-1,a_moire)*omega+b6(kx,ky,1,0,a_moire)*omega';...
        -(b6(kx,ky,0,-1,a_moire)+b6(kx,ky,1,1,a_moire)*omega'+b6(kx,ky,-1,0,a_moire)*omega)]...
        -i*t_ppz_neg*...
        [b6(kx,ky,0,-1,a_moire)+b6(kx,ky,1,1,a_moire)*omega+b6(kx,ky,-1,0,a_moire)*omega';...
        -(b6(kx,ky,0,1,a_moire)+b6(kx,ky,-1,-1,a_moire)*omega'+b6(kx,ky,1,0,a_moire)*omega)];

    C_kappap_pm=t_kappap_pm_pos*...
        [b6(kx,ky,-1,0,a_moire) b6(kx,ky,-1,-1,a_moire);...
        b6(kx,ky,-1,-1,a_moire)*omega' omega;...
        omega b6(kx,ky,-1,0,a_moire)*omega']-...
        t_kappap_pm_neg*...
        [b6(kx,ky,-1,-1,a_moire) b6(kx,ky,-1,0,a_moire);...
        omega' b6(kx,ky,-1,-1,a_moire)*omega;...
        b6(kx,ky,-1,0,a_moire)*omega omega'];

    H_kappa_1=t_kappa*...
        [0 b6(kx,ky,-1,0,a_moire) 1;...
        1 0 b6(kx,ky,0,-1,a_moire);...
        b6(kx,ky,1,1,a_moire) 1 0];
    H_kappa_2=t_kappa_prime*...
        [0 b6(kx,ky,-1,-1,a_moire) b6(kx,ky,-1,0,a_moire);...
        b6(kx,ky,0,-1,a_moire) 0 b6(kx,ky,1,0,a_moire);...
        b6(kx,ky,0,1,a_moire) b6(kx,ky,1,1,a_moire) 0];

    H_kappa=H_kappa_1+H_kappa_2+H_kappa_1'+H_kappa_2';

    H_k6=[H_pz+u_pz C_ppz' zeros(1,3);
        C_ppz H_p_pm+eye(2)*u_p_pm C_kappap_pm';
        zeros(3,1)  C_kappap_pm H_kappa+u_kappa*eye(3)];

    %% H64
    h_p_pos_A =[-(omega+omega'*b6(kx,ky,1,1,a_moire)+b6(kx,ky,0,1,a_moire))*Zeta'*a;...
        (omega'+omega*b6(kx,ky,1,1,a_moire)+b6(kx,ky,0,1,a_moire))*Zeta*b;...
        (1+b6(kx,ky,1,1,a_moire)+b6(kx,ky,0,1,a_moire))*c;...
        -i*b6(kx,ky,-1,0,a_moire)*d;...
        -i*omega*d;...
        -i*omega'*b6(kx,ky,0,1,a_moire)*d];
    
    h_p_neg_A=[(1+omega'*b6(kx,ky,1,1,a_moire)+b6(kx,ky,0,1,a_moire)*omega)*Zeta'*a;...
        (1+b6(kx,ky,1,1,a_moire)+b6(kx,ky,0,1,a_moire))*c;...
        (1+omega*b6(kx,ky,1,1,a_moire)+omega'*b6(kx,ky,0,1,a_moire))*Zeta*b;...
        -i*b6(kx,ky,-1,0,a_moire)*d;...
        -i*omega'*d;...
        -i*omega*b6(kx,ky,0,1,a_moire)*d];
    
    h_p_pos_B=[(omega+omega'*b6(kx,ky,1,0,a_moire)+b6(kx,ky,1,1,a_moire))*Zeta*a;...
        (omega'+omega*b6(kx,ky,1,0,a_moire)+b6(kx,ky,1,1,a_moire))*Zeta'*b;...
        (1+b6(kx,ky,1,0,a_moire)+b6(kx,ky,1,1,a_moire))*c;...
        i*d;...
        i*omega*d;...
        i*omega'*d];
    
    h_p_neg_B=[-(omega+b6(kx,ky,1,0,a_moire)+omega'*b6(kx,ky,1,1,a_moire))*Zeta*a;...
        (1+b6(kx,ky,1,0,a_moire)+b6(kx,ky,1,1,a_moire))*c;...
        (omega'+b6(kx,ky,1,0,a_moire)+omega*b6(kx,ky,1,1,a_moire))*Zeta'*b;...
        i*d;...
        i*omega'*d;...
        i*omega*d];  
    
    H64=[h_p_pos_A h_p_neg_A h_p_pos_B h_p_neg_B];
    %% H44 Kronecker product WITH identity matrix. is t_h multipul with fisrt matrix right?
    
     H44_A=[0 t_eta_psi*(1+b6(kx,ky,0,-1,a_moire)+b6(kx,ky,1,0,a_moire));...
        t_eta_psi'*(1+b6(kx,ky,0,1,a_moire)+b6(kx,ky,-1,0,a_moire)) 0];
 
     H44=kron(H44_A,eye(2));
     
     %% Construct hamiltonian.
     V_k_A=[u_pz C_ppz';...
         C_ppz H_p_pm+u_p_pm*eye(2)];
     V_k_B=[eye(3)*u_kappa zeros(3,4);...
         zeros(4,3) H44];
     V_k_C=[zeros(1,7);...
         C_kappap_pm' zeros(2,4)];
     V_k_D=[zeros(3,1) C_kappap_pm;...
         zeros(4,3)];
     V_k=[V_k_A V_k_C; ...
         V_k_D V_k_B];
     
     result=t_ham*[zeros(6,6) H64; H64' zeros(4,4)]...
         +deltaV*V_k;


end

